In [2]:
print("Hello, world!")

Hello, world!


In [1]:
#라이브러리로드
import numpy as np
print(np.__version__)

2.0.2


In [4]:
#다차원배열 생성
#벡터: 1차원배열,행렬: 2차원배열, 그 이후는 다차원 배열
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
test_array = np.array([1, 4, 5, "8"], float)
print(test_array)

[1. 4. 5. 8.]


In [6]:
print(type(test_array[3]))
# 실수형(floating Type)으로 자동 형 변환 실시

<class 'numpy.float64'>


In [7]:
print(test_array.dtype) # 배열 전체의 데이터 타입 반환

float64


In [8]:
print(test_array.shape) # 배열의 구조(shape)를 반환함

(4,)


In [9]:
matrix = [[1,2,5,8], [1,2,5,8], [1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [10]:
tensor_rank3 = [
        [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
        [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
        [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
        [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
        ]
np.array(tensor_rank3, int).shape

(4, 3, 4)

In [11]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])

In [14]:
import sys
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float64).itemsize

8

In [15]:
np.array( [[1, 2, 3.5], [4, 5, 6.5]], dtype=np.float32).itemsize

4

In [16]:
x = np.array([[1, 2, 5, 8], [1, 2, 5, 8]])
x.shape

(2, 4)

In [17]:
x.reshape(-1,)

array([1, 2, 5, 8, 1, 2, 5, 8])

In [18]:
x = np.array(range(8)).reshape(4,2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
x.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
x.reshape(2,2,-1)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [21]:
x = np.array(range(8)).reshape(2,2,2)
x

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [22]:
x.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [23]:
x = np.array([[1, 2, 3], [4, 5, 6]], int)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x[0][0]

np.int64(1)

In [25]:
x[0,2]

np.int64(3)

In [26]:
x = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
x[:,2:] # 전체 행의 2열 이상

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [27]:
x[1,1:3] # 1행의 1열 ~ 2열

array([7, 8])

In [28]:
x[1:3] # 1행 ~ 2행의 전체

array([[ 6,  7,  8,  9, 10]])

In [29]:
x = np.array(range(15), int).reshape(3, -1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
x[:,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14]])

In [31]:
x[::2,::3]

array([[ 0,  3],
       [10, 13]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(-5, 5)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [34]:
np.arange(0, 5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [35]:
np.ones(shape=(5,2), dtype=np.int8)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int8)

In [36]:
np.zeros(shape=(2,2), dtype=np.float32)

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [37]:
np.empty(shape=(2,4), dtype=np.float32)

array([[0.    , 1.875 , 0.    , 2.25  ],
       [0.    , 2.3125, 0.    , 2.5   ]], dtype=float32)

In [42]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
np.ones_like(x)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [44]:
np.zeros_like(x)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [45]:
np.identity(n=3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [46]:
np.identity(n=4, dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [47]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
np.eye(N=3, M=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [49]:
np.eye(N=3, M=5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
diag_elements = np.diag(arr)
print(diag_elements)

[1 5 9]


In [51]:
arr = np.array([1, 2, 3])
diag_matrix = np.diag(arr)
print(diag_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [52]:
np.diag(arr, k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [54]:
np.random.uniform(0, 5, 10)

array([4.46911197, 0.76960499, 2.03737981, 1.04776323, 3.83270216,
       0.74273704, 4.53062972, 0.29589473, 3.13902949, 0.09892116])

In [55]:
np.random.normal(0, 2, 10)

array([-4.14472197, -1.61116466, -0.30634923, -2.48967782, -0.19921301,
       -0.98891176,  0.59887596,  2.2314008 , -1.61057297,  3.2466855 ])

In [56]:
test_array = np.arange(1, 11)
test_array.sum()

np.int64(55)

In [57]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [59]:
test_array.sum(axis=1)

array([10, 26, 42])

In [60]:
test_array = np.arange(1, 13).reshape(3, 4)
third_order_tensor = np.array([test_array,test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [61]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [62]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [63]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [64]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
test_array.mean(axis=1) # axis=1 축을 기준으로 평균 연산

array([ 2.5,  6.5, 10.5])

In [66]:
test_array.std() # 전체 값에 대한 표준편차 연산

np.float64(3.452052529534663)

In [67]:
test_array.std(axis=0) # axis=0 축을 기준으로 표준편차 연산

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [68]:
np.sqrt(test_array) # 각 요소에 제곱근 연산 수행

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [69]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.vstack((v1, v2))

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6])

In [71]:
v1 = v1.reshape(-1, 1)
v2 = v2.reshape(-1, 1)
v1

array([[1],
       [2],
       [3]])

In [72]:
v2

array([[4],
       [5],
       [6]])

In [73]:
np.hstack((v1,v2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [74]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[4, 5, 6]])
np.concatenate((v1,v2), axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [75]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.concatenate((v1,v2), axis=0)

array([1, 2, 3, 4, 5, 6])

In [76]:
v1 = np.array([1, 2, 3, 4]).reshape(2,2)
v2 = np.array([[5,6]]).T
v1

array([[1, 2],
       [3, 4]])

In [77]:
v2

array([[5],
       [6]])

In [78]:
np.concatenate((v1,v2), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [79]:
x = np.arange(1, 7).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
x + x

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [81]:
x - x

array([[0, 0, 0],
       [0, 0, 0]])

In [82]:
x / x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [83]:
x ** x

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [85]:
x_1 = np.arange(1, 7).reshape(2,3)
x_2 = np.arange(1, 7).reshape(3,2)
x_1

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
x_2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
x_1.dot(x_2)

array([[22, 28],
       [49, 64]])

In [89]:
x = np.arange(1, 10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
x + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [91]:
x - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [92]:
x // 3

array([[0, 0, 1],
       [1, 1, 2],
       [2, 2, 3]])

In [93]:
x ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [94]:
x = np.arange(1, 13).reshape(4,3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
v = np.arange(10 , 40 , 10)
v

array([10, 20, 30])

In [96]:
x + v

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [97]:
import numpy as np
x = np.array([4, 3, 2, 6, 8, 5])
x > 3

array([ True, False, False,  True,  True,  True])

In [98]:
x = np.array([1, 3, 0])
y = np.array([2, 1, 7])
x > y

array([False,  True, False])

In [99]:
x = np.array([4, 6, 7, 3, 2])
(x > 3)

array([ True,  True,  True, False, False])

In [100]:
(x > 3).all()

np.False_

In [101]:
(x > 3).any()

np.True_

In [102]:
(x < 10).any()

np.True_

In [103]:
(x < 10).all()

np.True_

In [104]:
(x > 10).any()

np.False_

In [105]:
x = np.array([4, 6, 7, 3, 2])
x > 5

array([False,  True,  True, False, False])

In [106]:
np.where(x>5)

(array([1, 2]),)

In [107]:
x = np.array([4, 6, 7, 3, 2])
np.where(x>5 , 10, 20)

array([20, 10, 10, 20, 20])

In [108]:
x = np.array([4, 6, 7, 3, 2])
np.argsort(x)

array([4, 3, 0, 1, 2])

In [109]:
np.argmax(x)

np.int64(2)

In [110]:
np.argmin(x)

np.int64(4)

In [111]:
x = np.array([4, 6, 7, 3, 2])
x > 3

array([ True,  True,  True, False, False])

In [112]:
cond = x > 3
x[cond]

array([4, 6, 7])

In [113]:
x.shape

(5,)

In [114]:
cond.shape

(5,)

In [124]:
x = np.array([4, 6, 7, 3, 2])
cond = np.array([1, 2, 0, 2, 2, 2,], int)
x[cond]

array([6, 7, 4, 7, 7, 7])

In [125]:
x.take(cond)

array([6, 7, 4, 7, 7, 7])

In [117]:
x = np.array([[1,4], [9,16]], int)
a = np.array([0, 1, 1, 1, 0, 0], int)
b = np.array([0, 0, 0, 1, 1, 1], int)
x[a,b]

array([ 1,  9,  9, 16,  4,  4])